server:
  port: 14999
  address: 0.0.0.0
  network-thread-count: 1
  logic-thread-count: 2
player:
  maxOnline: 20
database:
  uri: mongodb://debian.mylab:27017
  db: cdf
path:
  js: '/home/alias/Projects/CyanDragonFish/javascripts'