// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cdf.Msg {

  /// <summary>Holder for reflection information generated from command.proto</summary>
  public static partial class CommandReflection {

    #region Descriptor
    /// <summary>File descriptor for command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jb21tYW5kLnByb3RvEgdjZGYubXNnKhQKB0NvbW1hbmQSCQoFSGVsbG8Q",
            "ACoTCglFcnJvckNvZGUSBgoCT0sQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cdf.Msg.Command), typeof(global::Cdf.Msg.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Command {
    [pbr::OriginalName("Hello")] Hello = 0,
  }

  public enum ErrorCode {
    [pbr::OriginalName("OK")] Ok = 0,
  }

  #endregion

}

#endregion Designer generated code
